### ISSUE TITLE
Сроки сдачи

### ISSUE THREAD

**Issue by marat-rkh** [vladimirrim/TelSC#37]
Напишите мне тут, пожалуйста, когда у вас дэлдайн.

**Comment by vladimirrim** [comment]
Скорее всего в понедельник.

**Comment by RamSaw** [comment]
Антон Михайлович сказал, что до 15:00 среды нужно выставить оценки за code review.

**Comment by marat-rkh** [comment]
А вы для работы над приложением использовали Android Studio?

**Comment by RamSaw** [comment]
Да.

**Comment by marat-rkh** [comment]
Написал Антону Михайловичу по поводу оценки, но он что то не отвечает с воскресенья. Если вам срочно надо с этим разобраться, свяжитесь, пожалуйста, с ним как нибудь, скажите что ревью закончено и узнайте в какой форме фидбэк от меня нужен.

**Comment by vladimirrim** [comment]
Фидбэк нужен в форме оценки от -0,5 до +0,5.

**Comment by marat-rkh** [comment]
Вымысле, а можно пояснение? Я с такой системой оценок не знаком.

**Comment by RamSaw** [comment]
Оценка складывается из двух: Антон Михайлович ставит от -0,5 до 0,5 за функциональность, Вы ставите от -0,5 до 0,5 за код. В итоге получается оценка от -1 до 1, которая повлияет на зачёт в конце весеннего семестра.

**Comment by marat-rkh** [comment]
То есть если я ставлю 0.5, то это значение прибавится к оценке итоговой? А отрицательные значения вычитаются из нее, да?

**Comment by vladimirrim** [comment]
Да.

**Comment by marat-rkh** [comment]
Мда, странная система. Ну ладно.
Давайте подведем итог. 
Основные положительные моменты: архитектура достаточно простая и понятная, разобраться в коде было не сложно. Сделали интеграцию со сторонней библиотекой, не смотря на сложности -- тоже плюс.
Основные отрицательные моменты: 
1) Работа с многопоточным и асинхронным кодом. Вам стоит получше разобраться в этой теме, потому что это очень важно. Многопоточный код везде. При этом, это область не такая простая, но что поделать. Советую почитать книгу Java concurrency in practice или хотя бы вот такую статью
https://habrahabr.ru/company/golovachcourses/blog/221133/
2) Неакктуратная работа с ресурсами, исключениями и null объектами. Нужно не забывать закрывать ресурсы, обрабатывать исключения и проверять результаты вызовов функций на null, так как если этого не делать, в работе программы будут серьезные проблемы.
3) Неряшливость кода. Было много лишнего кода, где то фигурные скобки потеряны, где то имена в разных кейсах, поля вместо локальных переменных и так далее. Все это вроде бы мелочи, но когда их много, это очень заметно. Хочется чтобы все было структурировано и аккуратно.

На основе всего этого, моя оценка: **-0.15.** Если у вас есть какие-то вопросы, вы с чем-то не согласны, буду рад обсудить.

Пояснение: честно говоря я вообще не понял эту систему оценок. Но если бы система была стандартная, то указанные недостатки работы точно бы привели к снижению итоговой оценки. Поэтому я поставил отрицательное значение.

**Comment by RamSaw** [comment]
А Антон Михайлович ещё не ответил про критерии оценки? Потому что мы можем ошибаться, в том как рассчитывается оценка. Вообще 0, насколько я помню - если в принципе нормальный код, ничего из ряда вон нет, ни положительного, ни отрицательного. Но я могу ошибаться.

**Comment by marat-rkh** [comment]
Пока не ответил.

**Comment by vladimirrim** [comment]
А вы учитывали только итоговый код или всю работу в целом?

**Comment by marat-rkh** [comment]
Ну ошибки, которые я описал, были у вас пока мы пыталсись привести код в порядок. Ревью -- просмотр кода на предмет проблем в нем. Так что видимо всю работу в целом.

**Comment by marat-rkh** [comment]
Антон Михайлович сказал что у вас не было многопоточности. Поэтому я решил повысить немного оценку. Теперь это -0.1. Антону Михайловичу сообщил.
